pull_request_rules:
  - name: automatic merge for master when reviewed and CI passes
    actions:
      merge:
        method: rebase
    conditions:
      - base=master
      - label=auto-merge
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - 'status-success=Specs | 2.4'
      - 'status-success=Specs | 2.5'
      - 'status-success=Specs | 2.6'
      - 'status-success=Specs | 2.7'
      - 'status-success=Specs | 3.0'
      - 'status-success=Specs | head'
      - 'status-success=Specs | mingw'
      - 'status-success=Coverage | 2.4'
      - 'status-success=Specs "modern" | 3.0'
      - 'status-success=Specs | jruby'
      - 'status-success=Specs | truffleruby'
      - 'status-success=Specs | truffleruby-head'
      - 'status-success=Main Gem Specs | RuboCop: v0.92.0 | 2.4'
      - 'status-success=Main Gem Specs | RuboCop: master | 2.4'
      - 'status-success=Main Gem Specs | RuboCop: v0.92.0 | 3.0'
      - 'status-success=Main Gem Specs | RuboCop: master | 3.0'
      - 'status-success=Coding Style | 2.7'

  - name: delete head branch after auto-merge
    conditions:
      - merged
      - label=auto-merge
    actions:
      delete_head_branch: {}
