# CAUTION: There's probably a way to refactor this nicely. PR welcome.
# NOTE: When changing minimal version of Ruby or Rubocop, change all of them

name: CI

on: [push, pull_request]

jobs:
  ast_specs:
    name: >-
      ${{ matrix.title || 'Specs' }} | RuboCop: ${{ matrix.rubocop }} | ${{ matrix.ruby }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    env:
      # See https://github.com/tmm1/test-queue#environment-variables
      TEST_QUEUE_WORKERS: 2
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        ruby: [ 2.4, 2.5, 2.6, 2.7, head ]
        rubocop: [ master ]
        coverage: [ null ]
        modern: [ null ]
        internal_investigation: [ null ]
        title: [ null ]
        include:
          - { os: windows, rubocop: master, ruby: mingw }
          - { rubocop: '0.87.0', ruby: 2.4, os: ubuntu }
          - { rubocop: '0.87.0', ruby: head, os: ubuntu }
          - { rubocop: '0.87.0', ruby: 2.4, os: ubuntu, coverage: true, title: 'Coverage' }
          - { rubocop: master, ruby: 2.7, os: ubuntu, modern: true, title: 'Specs "modern"' }
          - { rubocop: master, ruby: 2.7, os: ubuntu, internal_investigation: true, modern: true, title: 'Coding Style' }

    steps:
      - name: windows misc
        if: matrix.os == 'windows'
        run: |
          # set TMPDIR, git core.autocrlf
          echo "::set-env name=TMPDIR::$env:RUNNER_TEMP"
          git config --system core.autocrlf false
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: install dependencies
        run: bundle install --jobs 3 --retry 3
      - name: install rubocop packages for internal investigation
        if: matrix.os != 'windows'
        env:
          RUBOCOP_VERSION: ${{ matrix.rubocop }}
        run: bundle install --gemfile Gemfile.ci
      - name: install rubocop from source for internal investigation
        if: "matrix.os != 'windows' && matrix.rubocop == 'master'"
        run: |
          git clone https://github.com/rubocop-hq/rubocop.git ../rubocop
          chmod +x ../rubocop/exe/rubocop
          cd ../rubocop && bundle install --jobs 3 --retry 3
      - name: code coverage
        if: matrix.coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: '758a8228862932dc8afa9144c4a5bc5dfe29c2f7dde1b7734175bad49ee310e7'
          COVERAGE: 'true'
        with:
          coverageCommand: bundle exec rake spec
          debug: true
      - name: set modernize mode
        if: matrix.modern == true
        run: echo '::set-env name=MODERNIZE::true'
      - name: spec
        if: "matrix.coverage != true && matrix.internal_investigation != true"
        run:  bundle exec rake spec
      - name: internal investigation
        if: matrix.internal_investigation
        run:  bundle exec rake internal_investigation
  rubocop_specs:
    name: >-
      Main Gem Specs | RuboCop: ${{ matrix.rubocop }} | ${{ matrix.ruby }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    env:
      # See https://github.com/tmm1/test-queue#environment-variables
      TEST_QUEUE_WORKERS: 2
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        ruby: [ 2.4, 2.7 ]
        rubocop: [ '0.87.0', master ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: install dependencies
        run: bundle install --jobs 3 --retry 3
      - name: clone rubocop from source for full specs -- master
        if: matrix.rubocop == 'master'
        run: git clone --branch ${{ matrix.rubocop }} https://github.com/rubocop-hq/rubocop.git ../rubocop
      - name: install rubocop from source for full specs -- branch
        if: matrix.rubocop != 'master'
        run: git clone --branch v${{ matrix.rubocop }} https://github.com/rubocop-hq/rubocop.git ../rubocop
      - name: install rubocop dependencies
        run: cd ../rubocop && bundle install --jobs 3 --retry 3
      - name: spec
        run:  cd ../rubocop && bundle exec rake spec
