name: CI

on: [push, pull_request]

jobs:
  ast_specs:
    name: >-
      ${{ matrix.ruby }} | RuboCop ${{ matrix.rubocop }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    env:
      # See https://github.com/tmm1/test-queue#environment-variables
      TEST_QUEUE_WORKERS: 2
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        ruby: [ 2.4, 2.5, 2.6, 2.7, head ]
        rubocop: [ master ]
        # exclude:
        #   - { rubocop: '0.84.0' }
        include:
          - { os: windows, rubocop: master, ruby: mingw }
          - { rubocop: '0.84.0', ruby: 2.4, os: ubuntu }
          - { rubocop: '0.84.0', ruby: head, os: ubuntu }

    steps:
      - name: windows misc
        if: matrix.os == 'windows'
        run: |
          # set TMPDIR, git core.autocrlf
          echo "::set-env name=TMPDIR::$env:RUNNER_TEMP"
          git config --system core.autocrlf false
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: install dependencies
        run: bundle install --jobs 3 --retry 3
      - name: install rubocop packages for internal investigation
        if: matrix.os != 'windows'
        env:
          RUBOCOP_VERSION: ${{ matrix.rubocop }}
        run: bundle install --gemfile Gemfile.ci
      - name: install rubocop from source for internal investigation
        if: "matrix.os != 'windows' && matrix.rubocop == 'master'"
        run: |
          git clone https://github.com/rubocop-hq/rubocop.git ../rubocop
          chmod +x ../rubocop/exe/rubocop
          cd ../rubocop && bundle install --jobs 3 --retry 3
      - name: spec
        run:  bundle exec rake spec
      - name: internal_investigation
        if: matrix.os != 'windows'
        run:  bundle exec rake internal_investigation
  rubocop_specs:
    name: >-
      Full specs ${{ matrix.ruby }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    env:
      # See https://github.com/tmm1/test-queue#environment-variables
      TEST_QUEUE_WORKERS: 2
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        ruby: [ 2.4, 2.7 ]
        rubocop: [ master ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: install dependencies
        run: bundle install --jobs 3 --retry 3
      - name: install rubocop from source for internal investigation
        run: |
          git clone https://github.com/rubocop-hq/rubocop.git ../rubocop
          chmod +x ../rubocop/exe/rubocop
          cd ../rubocop && bundle install --jobs 3 --retry 3
      - name: spec
        run:  cd ../rubocop && bundle exec rake spec
